version: '3.8'

services:
  db-redis:
    image: 'redis:7.2'
    restart: 'unless-stopped'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
